parameters:
    draw.swagger.class: "Draw\\Swagger\\Swagger"
    draw.swagger.extrator.php_doc_operation_exractor.class: "Draw\\Swagger\\Extraction\\Extractor\\PhpDocOperationExtractor"
    draw.swagger.extrator.jms_extractor.class: "Draw\\Swagger\\Extraction\\Extractor\\JmsExtractor"
    draw.swagger.extrator.symfony_container_swagger_extractor.class: "Draw\\SwaggerBundle\\Extractor\\SymfonyContainerSwaggerExtractor"
    draw.swagger.extrator.fos_rest_route_operation_extractor.class: "Draw\\SwaggerBundle\\Extractor\\FOSRestRouteOperationExtractor"
    draw.swagger.extrator.route_operation_extractor.class: "Draw\\SwaggerBundle\\Extractor\\RouteOperationExtractor"
    draw.swagger.extrator.swagger_schema_extractor.class: "Draw\\Swagger\\Extraction\\Extractor\\SwaggerSchemaExtractor"
    draw.swagger.extractor.param_converter_extractor.class: "Draw\\SwaggerBundle\\Extractor\\ParamConverterExtractor"
    draw.swagger.extrator.type_schema_extractor.class: "Draw\\Swagger\\Extraction\\Extractor\\TypeSchemaExtractor"
    draw.swagger.extrator.fos_rest_view_operation_extractor.class: "Draw\\SwaggerBundle\\Extractor\\FOSRestViewOperationExtractor"

services:
    draw.swagger:
        class: '%draw.swagger.class%'
        arguments: ['@jms_serializer.serializer']

    draw.swagger.extrator.symfony_container_swagger_extractor:
        class: '%draw.swagger.extrator.symfony_container_swagger_extractor.class%'
        arguments: ['@annotation_reader']
        tags:
            - { name: swagger.extractor }

    draw.swagger.extrator.fos_rest_view_operation_extractor:
        class: '%draw.swagger.extrator.fos_rest_view_operation_extractor.class%'
        arguments: ['@annotation_reader', '@draw.serializer.group_hierarchy']
        tags:
            - { name: swagger.extractor }

    draw.swagger.extrator.swagger_tag_extractor:
        class: "Draw\\Swagger\\Extraction\\Extractor\\SwaggerTagExtractor"
        arguments: ['@annotation_reader']
        tags:
            - { name: swagger.extractor }

    draw.swagger.extrator.swagger_schema_extractor:
        class: '%draw.swagger.extrator.swagger_schema_extractor.class%'
        arguments: ['@jms_serializer.serializer']
        tags:
            - { name: swagger.extractor }

    draw.swagger.extrator.type_schema_extractor:
        class: '%draw.swagger.extrator.type_schema_extractor.class%'
        tags:
            - { name: swagger.extractor }

    draw.swagger.extrator.route_operation_extractor:
        class: '%draw.swagger.extrator.route_operation_extractor.class%'
        tags:
            - { name: swagger.extractor }

    draw.swagger.extrator.fos_rest_route_operation_extractor:
        class: '%draw.swagger.extrator.fos_rest_route_operation_extractor.class%'
        arguments: ['@fos_rest.request.param_fetcher.reader']
        tags:
            - { name: swagger.extractor }

    draw.swagger.extrator.jms_extractor:
        class: '%draw.swagger.extrator.jms_extractor.class%'
        arguments: ['@jms_serializer.metadata_factory', '@jms_serializer.naming_strategy']
        tags:
            - { name: swagger.extractor }

    draw.swagger.jms_serializer_listener:
        class: "Draw\\Swagger\\JMSSerializerListener"
        tags:
            - { name: jms_serializer.event_subscriber }

    draw.swagger.extractor.constraint_extractor:
        abstract:  true
        calls:
            - [setMetadataFactory, ['@validator.mapping.class_metadata_factory']]

    draw.swagger.extractor.constraint_extractor.not_null:
        parent: draw.swagger.extractor.constraint_extractor
        class: "Draw\\Swagger\\Extraction\\Extractor\\Constraint\\NotNullConstraintExtractor"

    draw.swagger.extractor.constraint_extractor.choice:
        parent: draw.swagger.extractor.constraint_extractor
        class: "Draw\\Swagger\\Extraction\\Extractor\\Constraint\\ChoiceConstraintExtractor"

    draw.swagger.extractor.constraint_extractor.not_blank:
        parent: draw.swagger.extractor.constraint_extractor
        class: "Draw\\Swagger\\Extraction\\Extractor\\Constraint\\NotBlankConstraintExtractor"

    draw.swagger.extractor.constraint_extractor.range:
        parent: draw.swagger.extractor.constraint_extractor
        class: "Draw\\Swagger\\Extraction\\Extractor\\Constraint\\RangeConstraintExtractor"

    draw.swagger.extractor.constraint_extractor.length:
        parent: draw.swagger.extractor.constraint_extractor
        class: "Draw\\Swagger\\Extraction\\Extractor\\Constraint\\LengthConstraintExtractor"

    draw.swagger.extractor.constraint_extractor.count:
        parent: draw.swagger.extractor.constraint_extractor
        class: "Draw\\Swagger\\Extraction\\Extractor\\Constraint\\CountConstraintExtractor"

    draw.swagger.extrator.php_doc_operation_exractor:
        class: '%draw.swagger.extrator.php_doc_operation_exractor.class%'
        tags:
            - { name: swagger.extractor }

    draw.swagger.extractor.param_converter_extractor:
        class: '%draw.swagger.extractor.param_converter_extractor.class%'
        arguments: ['@annotations.reader', '@draw.serializer.group_hierarchy']
        tags:
            - { name: swagger.extractor }